<a href="https://colab.research.google.com/github/AHANIK33/Deep-Learning/blob/main/Student_result.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report
import joblib

In [6]:
df = pd.read_csv('/content/student.csv')
df

     study_hours  attendance  previous_marks  assignment_score  result
0              7          81              73                61       1
1              4          68              79                66       1
2              8          73              87                84       1
3              5          93              76                95       1
4              7          90              73                85       1
..           ...         ...             ...               ...     ...
295            1          65              38                52       0
296            5          80              90                35       1
297            6          97              59                81       1
298            3          67              37               100       0
299            9          60              66                72       1

[300 rows x 5 columns]

In [7]:
df.shape

(300, 5)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   study_hours       300 non-null    int64
 1   attendance        300 non-null    int64
 2   previous_marks    300 non-null    int64
 3   assignment_score  300 non-null    int64
 4   result            300 non-null    int64
dtypes: int64(5)
memory usage: 11.8 KB

In [15]:
df.describe()

       study_hours  attendance  previous_marks  assignment_score     result
count   300.000000  300.000000      300.000000        300.000000  300.00000
mean      5.326667   73.740000       62.193333         67.166667    0.54000
std       2.873001   15.661738       16.589958         19.184866    0.49923
min       1.000000   45.000000       35.000000         35.000000    0.00000
25%       3.000000   61.000000       47.000000         51.000000    0.00000
50%       5.000000   74.000000       62.000000         67.000000    1.00000
75%       8.000000   87.000000       77.000000         84.000000    1.00000
max      10.000000  100.000000       90.000000        100.000000    1.00000

In [12]:
df.isnull().sum()

study_hours         0
attendance          0
previous_marks      0
assignment_score    0
result              0
dtype: int64

In [14]:
df['result'].value_counts()

result
1    162
0    138
Name: count, dtype: int64

In [16]:
X = df.drop('result', axis=1)
y = df['result']

In [17]:
X_train,X_temp,y_train,y_temp = train_test_split(X,y,test_size=0.2,random_state=42)
X_val,X_test,y_val,y_test = train_test_split(X_temp,y_temp,test_size=0.5,random_state=42)

In [26]:
Scaler = StandardScaler()

In [31]:
X_train = Scaler.fit_transform(X_train)

X_val = Scaler.transform(X_val)

X_test = Scaler.transform(X_test)

In [33]:
X_train_tensor = torch.tensor(X_train,dtype = torch.float32)
y_train_tensor = torch.tensor(y_train.values,dtype = torch.long)
X_val_tensor = torch.tensor(X_val,dtype = torch.float32)
y_val_tensor = torch.tensor(y_val.values,dtype = torch.long)
X_test_tensor = torch.tensor(X_test,dtype = torch.float32)
y_test_tensor = torch.tensor(y_test.values,dtype = torch.long)

In [35]:
train_dataset = TensorDataset(X_train_tensor,y_train_tensor)
val_dataset = TensorDataset(X_val_tensor,y_val_tensor)
test_dataset = TensorDataset(X_test_tensor,y_test_tensor)

In [36]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
val_loader = DataLoader(val_dataset,batch_size=32)
test_loader = DataLoader(test_dataset,batch_size=32)

In [58]:
class MyNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.model = nn.Sequential(
        nn.Linear(num_features,64),
        nn.ReLU(),
        nn.Linear(64,32),
        nn.ReLU(),
        nn.Linear(32,2)
    )

  def forward(self,X):
   return self.model(X)

In [59]:
epochs = 100
learning_rate = 0.001

In [60]:
model = MyNN(X_train.shape[1])
print(model)

MyNN(
  (model): Sequential(
    (0): Linear(in_features=4, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=32, bias=True)
    (3): ReLU()
    (4): Linear(in_features=32, out_features=2, bias=True)
  )
)

In [61]:
criterion = nn.CrossEntropyLoss()

In [62]:
optimizer = optim.Adam(model.parameters(),lr=0.001)

In [63]:
for epoch in range(epochs):
  total_epoch_loss = 0
  for batch_features, batch_labels in train_loader:
    batch_features = batch_features
    batch_labels = batch_labels
    optimizer.zero_grad()
    outputs = model(batch_features)
    loss = criterion(outputs,batch_labels)
    loss.backward()
    optimizer.step()
    total_epoch_loss += loss.item()
  avg_loss = total_epoch_loss / len(train_loader)
  print(f"Epoch {epoch+1}/{epochs}, Loss: {avg_loss:.4f}")

Epoch 1/100, Loss: 0.6568
Epoch 2/100, Loss: 0.6147
Epoch 3/100, Loss: 0.5704
Epoch 4/100, Loss: 0.5150
Epoch 5/100, Loss: 0.4633
Epoch 6/100, Loss: 0.4183
Epoch 7/100, Loss: 0.3741
Epoch 8/100, Loss: 0.3659
Epoch 9/100, Loss: 0.3371
Epoch 10/100, Loss: 0.3263
Epoch 11/100, Loss: 0.3180
Epoch 12/100, Loss: 0.3084
Epoch 13/100, Loss: 0.3189
Epoch 14/100, Loss: 0.3090
Epoch 15/100, Loss: 0.3100
Epoch 16/100, Loss: 0.3066
Epoch 17/100, Loss: 0.3095
Epoch 18/100, Loss: 0.2871
Epoch 19/100, Loss: 0.3028
Epoch 20/100, Loss: 0.2892
Epoch 21/100, Loss: 0.2903
Epoch 22/100, Loss: 0.2765
Epoch 23/100, Loss: 0.2840
Epoch 24/100, Loss: 0.2783
Epoch 25/100, Loss: 0.2893
Epoch 26/100, Loss: 0.2786
Epoch 27/100, Loss: 0.2944
Epoch 28/100, Loss: 0.2745
Epoch 29/100, Loss: 0.2687
Epoch 30/100, Loss: 0.2862
Epoch 31/100, Loss: 0.2767
Epoch 32/100, Loss: 0.2690
Epoch 33/100, Loss: 0.2718
Epoch 34/100, Loss: 0.2585
Epoch 35/100, Loss: 0.2659
Epoch 36/100, Loss: 0.2624
Epoch 37/100, Loss: 0.2641
Epoch 38/100, Loss: 0.2622
Epoch 39/100, Loss: 0.2616
Epoch 40/100, Loss: 0.2525
Epoch 41/100, Loss: 0.2659
Epoch 42/100, Loss: 0.2491
Epoch 43/100, Loss: 0.2585
Epoch 44/100, Loss: 0.2451
Epoch 45/100, Loss: 0.2567
Epoch 46/100, Loss: 0.2603
Epoch 47/100, Loss: 0.2537
Epoch 48/100, Loss: 0.2401
Epoch 49/100, Loss: 0.2478
Epoch 50/100, Loss: 0.2466
Epoch 51/100, Loss: 0.2444
Epoch 52/100, Loss: 0.2338
Epoch 53/100, Loss: 0.2383
Epoch 54/100, Loss: 0.2435
Epoch 55/100, Loss: 0.2304
Epoch 56/100, Loss: 0.2434
Epoch 57/100, Loss: 0.2258
Epoch 58/100, Loss: 0.2207
Epoch 59/100, Loss: 0.2289
Epoch 60/100, Loss: 0.2225
Epoch 61/100, Loss: 0.2284
Epoch 62/100, Loss: 0.2329
Epoch 63/100, Loss: 0.2264
Epoch 64/100, Loss: 0.2188
Epoch 65/100, Loss: 0.2190
Epoch 66/100, Loss: 0.2212
Epoch 67/100, Loss: 0.2244
Epoch 68/100, Loss: 0.2304
Epoch 69/100, Loss: 0.2223
Epoch 70/100, Loss: 0.2302
Epoch 71/100, Loss: 0.2153
Epoch 72/100, Loss: 0.2175
Epoch 73/100, Loss: 0.2124
Epoch 74/100, Loss: 0.2027
Epoch 75/100, Loss: 0.2144
Epoch 76/100, Loss: 0.2097
Epoch 77/100, Loss: 0.2079
Epoch 78/100, Loss: 0.2146
Epoch 79/100, Loss: 0.2028
Epoch 80/100, Loss: 0.1984
Epoch 81/100, Loss: 0.2071
Epoch 82/100, Loss: 0.1968
Epoch 83/100, Loss: 0.2085
Epoch 84/100, Loss: 0.2022
Epoch 85/100, Loss: 0.1952
Epoch 86/100, Loss: 0.1939
Epoch 87/100, Loss: 0.1958
Epoch 88/100, Loss: 0.2025
Epoch 89/100, Loss: 0.1919
Epoch 90/100, Loss: 0.1949
Epoch 91/100, Loss: 0.1902
Epoch 92/100, Loss: 0.1963
Epoch 93/100, Loss: 0.1911
Epoch 94/100, Loss: 0.1819
Epoch 95/100, Loss: 0.2021
Epoch 96/100, Loss: 0.1874
Epoch 97/100, Loss: 0.1906
Epoch 98/100, Loss: 0.1788
Epoch 99/100, Loss: 0.1825
Epoch 100/100, Loss: 0.1821

In [65]:
model.eval()

correct = 0
total = 0

with torch.no_grad():
  for X_batch,y_batch in val_loader:
    output = model(X_batch)

    _, pred = torch.max(output, 1)
    correct += (pred == y_batch).sum().item()
    total += y_batch.size(0)

accuracy = correct / total
print(f"Validation Accuracy: {accuracy:.4f}")

Validation Accuracy: 1.0000

In [67]:
epochs = 20
train_losses = []
val_losses = []

train_accuracy = []
val_accuracy = []

for epoch in range(epochs):
  model.train()
  running_loss = 0
  correct = 0
  total = 0

  for X_batch, y_batch in train_loader:
    optimizer.zero_grad()
    outputs = model(X_batch).squeeze()
    loss = criterion(outputs,y_batch)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
    _,pred = torch.max(outputs,1)
    correct += (pred == y_batch).sum().item()
    total += y_batch.size(0)

  train_loss = running_loss / len(train_loader)
  train_acc = correct / total

In [71]:
train_losses = []
val_losses = []

train_accuracy = []
val_accuracy = []

for epoch in range(epochs):
  model.train()
  val_running_loss = 0
  val_correct = 0
  val_total = 0

  for X_batch, y_batch in val_loader:
    optimizer.zero_grad()
    outputs = model(X_batch).squeeze()
    loss = criterion(outputs,y_batch)
    loss.backward()
    optimizer.step()
    val_running_loss += loss.item()
    _,pred = torch.max(outputs,1)
    val_correct += (pred == y_batch).sum().item()
    val_total += y_batch.size(0)

  val_train_loss = running_loss / len(train_loader)
  val_train_acc = correct / total

In [72]:
train_losses.append(train_loss)
val_losses.append(val_train_loss)

train_accuracy.append(train_acc)
val_accuracy.append(val_train_acc)

In [73]:
print(f"Epoch {epoch+1}/{epochs}, Training Loss: {train_loss:.4f}, Validation Loss: {val_train_loss:.4f}")
print(f"Epoch {epoch+1}/{epochs}, Training Accuracy: {train_acc:.4f}, Validation Accuracy: {val_train_acc:.4f}")

Epoch 20/20, Training Loss: 0.1640, Validation Loss: 0.1640
Epoch 20/20, Training Accuracy: 0.9333, Validation Accuracy: 0.9333

In [86]:
model.eval()

all_predictions = []
all_actuals = []

with torch.no_grad():
  for X_batch, y_batch in test_loader:
    outputs = model(X_batch)
    _, pred = torch.max(outputs,1)
    all_predictions.extend(pred.cpu().numpy())
    all_actuals.extend(y_batch.cpu().numpy())

In [89]:
accuracy = accuracy_score(
    all_actuals,
    all_predictions
)

precision = precision_score(
    all_actuals,
    all_predictions
)

recall = recall_score(
    all_actuals,
    all_predictions
)

f1 = f1_score(
    all_actuals,
    all_predictions
)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.8333333333333334
Precision: 0.9230769230769231
Recall   : 0.75
F1 Score : 0.8275862068965517

In [90]:
print(
    classification_report(
        all_actuals,
        all_predictions
    )
)

              precision    recall  f1-score   support

           0       0.76      0.93      0.84        14
           1       0.92      0.75      0.83        16

    accuracy                           0.83        30
   macro avg       0.84      0.84      0.83        30
weighted avg       0.85      0.83      0.83        30

In [91]:
torch.save(model.state_dict(),"student_model.pth")

In [94]:
joblib.dump(Scaler,"student_scaler.pkl")

['student_scaler.pkl']

In [99]:
model = MyNN(X_train.shape[1])

model.load_state_dict(
    torch.load(
        "student_model.pth",
        weights_only=True
    )
)

model.eval()

MyNN(
  (model): Sequential(
    (0): Linear(in_features=4, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=32, bias=True)
    (3): ReLU()
    (4): Linear(in_features=32, out_features=2, bias=True)
  )
)

In [122]:
new_student = np.array([
    [6, 85, 70, 75]
])

In [102]:
new_student_scaled = Scaler.transform(
    new_student
)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [103]:
new_student_tensor = torch.tensor(
    new_student_scaled,
    dtype=torch.float32
)

In [106]:
model.eval()

with torch.no_grad():

    output = model(new_student_tensor)


    _, prediction = torch.max(output, 1)


    prediction = prediction.item()

In [108]:
if prediction == 1:
    print("Pass")
else:
    print("Fail")

Pass